export const HOME = '/home'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const INICIO= '/inicio'
export const ZONA= '/zona'
export const CARDS= '/cards'
export const RUTA1= '/ruta1'
export const RUTA2= '/ruta2'